employee_name = str(input('Enter Name: '))
employee_ssn = str(input('Enter Social Security Number: '))
employee_phone = str(input('Enter Phone number: '))
employee_email = str(input('Enter Email: '))
employee_salary = int(input('Enter Annual Salary: '))

print(f'----------------{employee_name}----------------', '\n')
print(f'SSN: {employee_ssn[:3]}-{employee_ssn[3:5]}-{employee_ssn[5:]}', '\n')
print(f'Phone: ({employee_phone[:3]}) {employee_phone[3:6]}-{employee_phone[6:]}', '\n')
print(f'Email: {employee_email}', '\n')
print(f'Salary: ${employee_salary:,.2f}', '\n')
print('-----------------------------------------------', '\n')